#!/usr/bin/env bash
set -Eeuo pipefail
HERE="$(cd -- "$(dirname -- "$0")" && pwd)"
BASE="$HERE/build_p5_multicore_performance2.sh"
[[ -f "$BASE" ]] || { echo "ERROR: missing $BASE" >&2; exit 2; }
: "${P5_SUPER_MTU:=1500}"; : "${P5_SUPER_CACHE:=128}"; : "${P5_SUPER_RX_BURST:=32}"; : "${P5_SUPER_TX_BURST:=16}"; : "${P5_SUPER_RING_SIZE:=4096}"; : "${P5_SUPER_RING_SYNC:=legacy}"; : "${P5_SUPER_DRAIN_BURSTS:=2}"; : "${P5_SUPER_DRAIN_THRESHOLD:=0}"; : "${P5_SUPER_SKIP_OFF_RINGCOUNT:=0}"; : "${P5_SUPER_DEBUG_COUNTERS:=1}"; : "${P5_SUPER_TRACE_RINGCOUNT:=1}"; : "${P5_P2_TX_HANDOFF:=shared}"; : "${P5_P2_TX_PRODUCER_RING_SIZE:=1024}"; : "${P5_P2_RX_PREFETCH:=0}"; : "${P5_P2_UDP_SEG:=0}"; : "${P5_P2_UDP_SEG_MAX:=4}"; : "${P5_P2_TX_ALLOC_BATCH:=8}"; : "${P5_P2_TX_ENQUEUE_COUNTER:=0}"; : "${P5_P2_TX_META_ZERO:=1}"; : "${P5_P2_RX_PIPE_PREFETCH:=2}"; : "${P5_P2_SHARD_ACTIVE_MASK:=0}"; : "${P5_ARCH_MBUF_POOL_SIZE:=32767}"
export P5_BUILD_REUSE=1 P5_SUPER_MTU P5_SUPER_CACHE P5_SUPER_RX_BURST P5_SUPER_TX_BURST P5_SUPER_RING_SIZE P5_SUPER_RING_SYNC P5_SUPER_DRAIN_BURSTS P5_SUPER_DRAIN_THRESHOLD P5_SUPER_SKIP_OFF_RINGCOUNT P5_SUPER_DEBUG_COUNTERS P5_SUPER_TRACE_RINGCOUNT P5_P2_TX_HANDOFF P5_P2_TX_PRODUCER_RING_SIZE P5_P2_RX_PREFETCH P5_P2_UDP_SEG P5_P2_UDP_SEG_MAX P5_P2_TX_ALLOC_BATCH P5_P2_TX_ENQUEUE_COUNTER P5_P2_TX_META_ZERO P5_P2_RX_PIPE_PREFETCH P5_P2_SHARD_ACTIVE_MASK P5_ARCH_MBUF_POOL_SIZE
printf 'ARCH BUILD: ring_sync=%s udp_seg=%s txhandoff=%s mtu=%s mbuf_pool=%s\n' "$P5_SUPER_RING_SYNC" "$P5_P2_UDP_SEG" "$P5_P2_TX_HANDOFF" "$P5_SUPER_MTU" "$P5_ARCH_MBUF_POOL_SIZE"
bash "$BASE"
